# test nanoplot.

rule nanoplot_fastq:
    input:
        fastqs = ["test.fq.gz"]
    output:
        html = "nanoplot_fq/test.NanoPlot-report.html"
    params:
        title = "test.fq",
        extras = "--tsv_stats --N50"
    wrapper:
        "master/bio/nanopack/nanoplot"

rule nanoplot_bam:
    input:
        bams = ["test.bam"]
    output:
        html = "nanoplot_bam/test.NanoPlot-report.html"
    params:
        title = "test.bam",
        extras = "--tsv_stats --N50"
    wrapper:
        "master/bio/nanopack/nanoplot"
