name: nanofilt
description: nanofilt from nanopack.
url: https://github.com/wdecoster/nanofilt
authors:
    - yangqun
input:
    - fastq: "input fastq file. can be gziped.(such as, fastq, fastq.gz, fq, fq.gz)."
output:
    - out: "filtered fastq file. same as the input."
params:
    - nanofilt: "nanofilt path (optional)."
    - min_len: "filter on minimum read length (optional)."
    - max_len: "filter on maximum read length (optional)."
    - extras: "extra arguments to nanofilt (optional)."
