name: nanoplot
description: nanoplot from nanopack.
url: https://github.com/wdecoster/nanoplot
authors:
    - yangqun
input:
    - fastqs: "input fastqs list, not with bams."
    - bams: "input bams list, not with fastqs."
output:
    - html: "xxx.NanoPlot-report.html. full path to html summary report. Using for parse outdir and prefix."
params:
    - title: "title name in plot.(optional)"
    - extras: "extra arguments add to nanoplot.(optional)"
