name: trimmomatic
description: trimmomatic for illumina data.
url: http://www.usadellab.org/cms/?page=trimmomatic
authors:
    - yangqun
input:
    - data: "input fastq (list)"
    - trimmomatic: "trimmomatic jar."
    - adpaters: "adapter file."
    - java: "java cmd path. (optional)"    
output:
    - outfiles: "4 files or 1 file, list."
params:
    - extras: "extra arguments to fastqc. (optional)"
