name: chopper
description: chopper from nanopack.
url: https://github.com/wdecoster/chopper
authors:
    - yangqun
input:
    - fastqs: "input fastq files list, can be gziped.(such as, fastq, fastq.gz, fq, fq.gz). All file must be the same file type."
output:
    - out: "filtered fastq file, same as the input."
params:
    - chopper: "path to chopper, (optional). default is chopper."
    - quality: "minimum Phred average quality score. (optional), default is 0."
    - min_len: "filter on minimum read length (optional). default is 1."
    - max_len: "filter on maximum read length (optional). default is 2147483647."
    - headcrop: "Trim N nucleotides from the start of a read. (optional), default is 0."
    - tailcrop: "Trim N nucleotides from the end of a read. (optional), default is 0."
    - extras: "extra arguments to chopper (optional)."
