name: mosdepth
description: fast BAM/CRAM depth calculation for WGS, exome, or targeted sequencing.
url: https://github.com/brentp/mosdepth
authors:
    - yangqun
input:
    - bam: "input bam file."
    - bai: "input bam index."
output:
    - summary: "xxx.mosdepth.summary.txt."
params:
    - mosdepth: "mosdepth path. default mosdepth. (optional)"
    - by: "bin size or bed file. default none. (optional)"
    - thresholds: "thresholds. default none. (optional)"
    - extras: "extra arguments. (optional)"
note: "parse prefix according summary."
