name: hello_world
description: a test wrapper. just print hello world or name.
url: https://github.com/conanyangqun/snakemake-wrappers-yq
authors:
    - yangqun
input:
output:
params:
    name: give some name.
notes:
