name: downsample
description: downsample bam using samtools view.
url: https://github.com/samtools/samtools
authors:
    - yangqun
input:
    - bam: "input bam."
output:
    - bam: "downsampled bam."
    - bai: "bam index.(optional)"
params:
    - extras: "-s <float>"
note:
    "downsample bam. index it."
 